### ISSUE TITLE
Provided post date is ignored

### ISSUE THREAD

**Issue by ineeee** [camconn/shim#10]
Basically this doesn't do anything

![](https://puu.sh/nyBBB.png)

**Comment by camconn** [comment]
Yeah currently it's only updated on post publishing. I'm looking into a possible fix.

**Comment by camconn** [comment]
I modified the front end for shim to only provide the option for editing a post's date whenever the post is actually published. In the event a post is _not_ published, a message is provided to the user with the post's date.

In the event that a user wants to modify the post's date, the should simply edit the post and modify the `published` option.

Mark as resolved and close if you think this behavior is appropriate. If not, then please elaborate.

**Comment by camconn** [comment]
Fixed as of 0cd5ce4c179490efa276ebe1b62a36081cb6f45d

**Comment by ineeee** [comment]
Nice
