### ISSUE TITLE
Replace Viper with another TOML parser

### ISSUE THREAD

**Issue by camconn** [camconn/shim#11]
It's time to de-cruft shim. Right now, viper is _incredibly_ heavy, and has so many extra features and useless things for our use-cases.

It's time to find a different TOML parser or maybe even move on to YAML or JSON.

Here's a list of possible TOML parsers we can use in the future:
- https://github.com/naoina/toml
- https://github.com/pelletier/go-toml
- https://github.com/kezhuw/toml
- https://github.com/BurntSushi/toml (outdated, but used internally by viper)
- https://github.com/achun/tom-toml (outdated)

Asking for recommendations from @inexist3nce and @niemal on this one.

**Comment by ineeee** [comment]
whats wrong with burntsushi's toml aren't we already using it

**Comment by camconn** [comment]
You're right.

We're going to use https://github.com/BurntSushi/toml as that's what viper uses under the hood for TOML parsing. That will be good enough.

**Comment by camconn** [comment]
There is nothing to really worry about here, so I'm closing this issue.

**Comment by ineeee** [comment]
whoa youre alive
