### ISSUE TITLE
Make the Page Editor Prettier

### ISSUE THREAD

**Issue by camconn** [camconn/shim#12]
We need things to be shiny. I know @inexist3nce had a pretty good prototype in the works.

Here is a laundry list of things that would be really cool, but aren't necessarily required:
- Link Insertion
- Bold
- Italics
- Underline
- Drag + Drop image support
- Header support (and subsection) support
- Maybe have tabs to show post previews in-line (using bulma's tabbed `nav`)
- <kbd>Ctrl</kbd> + <kbd>S</kbd> to save a post being edited
- Have cute icons

**Comment by ineeee** [comment]
I have to deal with the changes in your latest commit, I'll do it tomorrow

**Comment by ineeee** [comment]
This ended up being very easy: https://github.com/NextStepWebs/simplemde-markdown-editor

But it has a specific feature that in my opinion only adds bloat, basic english spell check: https://github.com/NextStepWebs/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L1149

**Comment by camconn** [comment]
I'm okay with removing the spell check, as the vast majority of browsers support spell checking. [95 % of browsers in the world](http://caniuse.com/#feat=spellcheck-attribute) support the `spellcheck` attribute though, so just make sure to use that.

Thanks for the help.

**Comment by ineeee** [comment]
Done

**Comment by camconn** [comment]
:+1: 

@inexist3nce rox
