### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by ineeee** [camconn/shim#8]
I didn't code with small screens in mind, its probably all broken and stuff.

TODO: Make shim responsive

**Comment by camconn** [comment]
Actually, I see no current issues as far as the UI is concerned. Shim is responsive for the all of vertical resolutions (that I tested), and responsive for horizontal as low as 300px.

That's pretty good, all things considered. Close this issue and mark as invalid if that's acceptable.

**Comment by ineeee** [comment]
I thought I closed this a week ago. Sorry.
