### ISSUE TITLE
Sessions are pain

### ISSUE THREAD

**Issue by ineeee** [camconn/shim#9]
Login session don't last more than a few seconds, and it seems like `/preview/` completely logs out the user. Its stupid to have to log in every time I click on something.

Also I lost the contents of my post because I got redirected to the login page.

**Comment by niemal** [comment]
For fuck's sake get on your bouncer on freenode.

**Comment by ineeee** [comment]
rip hydrarino

**Comment by ineeee** [comment]
also i blame you for glitchy sessions

**Comment by niemal** [comment]
Okay, sessions work as they should now. https://github.com/niemal/uman/commit/55e41e29907680b474b39bb1755d07be8d082f2e
